# Generated by Django 5.2.5 on 2025-11-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_usercontext_background_institution_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontext',
            name='background_level',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='usercontext',
            name='diagnostic_snapshot',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='usercontext',
            name='diagnostic_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usercontext',
            name='self_assessment',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
