from django.urls import path
from .views import (
    IndexDocumentView,
    SearchView,
    ChatView,
    ChatSSEView,
    StudyPlanListView,
    GenerateStudyPlanView,
    StudyPlanDetailView,
    StudyPlanWeekView,
    StudyTaskProgressView,
    GenerateSectionTasksView,
    GenerateStudyDayView,
    StudyPlanDayCreateView,
    StudyDayResultView,
    StudyPlanMaterialUploadView,
    JobStatusView,
    JobStreamView,
)

urlpatterns = [
    path("index/", IndexDocumentView.as_view()),
    path("search/", SearchView.as_view()),
    path('chat/', ChatView.as_view(), name='ai_chat'),
    path('chat/stream/', ChatSSEView.as_view(), name='ai_chat_stream'),
    path("study-plans/", StudyPlanListView.as_view(), name="study_plan_list"),
    path("study-plans/generate/", GenerateStudyPlanView.as_view(), name="generate_study_plan"),
    path("study-plans/<uuid:plan_id>/", StudyPlanDetailView.as_view(), name="study_plan_detail"),
    path("study-plans/<uuid:plan_id>/weeks/", StudyPlanWeekView.as_view(), name="study_plan_weeks"),
    path("study-plans/<uuid:plan_id>/days/", StudyPlanDayCreateView.as_view(), name="study_plan_day_create"),
    path("study-plans/<uuid:plan_id>/days/<uuid:day_id>/generate/", GenerateStudyDayView.as_view(), name="study_plan_day_generate"),
    path("study-plans/<uuid:plan_id>/days/<uuid:day_id>/results/", StudyDayResultView.as_view(), name="study_day_results"),
    path("study-plans/<uuid:plan_id>/tasks/", GenerateSectionTasksView.as_view(), name="study_plan_tasks"),
    path("study-plans/<uuid:plan_id>/materials/", StudyPlanMaterialUploadView.as_view(), name="study_plan_material"),
    path("study-tasks/<uuid:task_id>/progress/", StudyTaskProgressView.as_view(), name="study_task_progress"),
    path("jobs/<str:job_id>/", JobStatusView.as_view(), name="job_status"),
    path("jobs/stream/", JobStreamView.as_view(), name="job_stream"),
]
